Généralisation des Category Field
jeremy-wdf/wonderwp pull request #21
Opened 2017-05-10 14:17 UTC by MonsieurLuge

Ajout d'une classe abstraite "AbstractCategoryField" qui se charge de la récupération et de l'initialisation des catégories / options par défaut.

Création de deux classes qui étendent cette classe abstraite:
 - RawCategoryField, qui ajoute aux options les noms des catégories
 - TranslatedCategoryField, qui ajoute aux options le terme traduit (term_ + slug) des catégories

2017-05-10 15:16 UTC, jdm-web requested changes

2017-05-10 15:16 UTC, jeremy-wdf commented on src/WonderWp/Framework/Form/Field/AbstractCategoryField.php
> +    }
checker une displayRules['firtOptionLabel'], si non on prend displayRules['label'] si non ' '

2017-05-10 15:16 UTC, jeremy-wdf commented on src/WonderWp/Framework/Form/Field/AbstractCategoryField.php
> +    }
Donner la possibilité de passer les attributs de la requête en params, faire des default params et utiliser le merge des 2 dans la requête

2017-05-10 15:16 UTC, jeremy-wdf commented on src/WonderWp/Framework/Form/Field/RawCategoryField.php
> +<?php
Ne pas utiliser cet objet, le faire dans CategoryField direct

2017-05-10 15:16 UTC, jeremy-wdf commented on src/WonderWp/Framework/Form/Field/CategoryField.php
> +// @deprecated
Ne pas déprécier cet objet, le merger avec RawCategoryField

2017-05-10 15:16 UTC, jeremy-wdf commented on src/WonderWp/Framework/Form/Field/TranslatedCategoryField.php
> +            $this->selectOptions[$category->term_id] = __('term_' . $category->slug, $this->getTextDomain());
Descendre getTextDomain dans cette classe

2017-05-10 15:16 UTC, jeremy-wdf commented on src/WonderWp/Framework/Form/Field/AbstractCategoryField.php
> +    protected function getTextDomain()
A supprimer

2017-05-10 15:16 UTC, jeremy-wdf commented on src/WonderWp/Framework/Form/Field/TranslatedCategoryField.php
> +class TranslatedCategoryField extends AbstractCategoryField implements OptionsFieldInterface
je préfère sans l'implements

2017-05-10 15:16 UTC, jeremy-wdf commented on src/WonderWp/Framework/Form/Field/RawCategoryField.php
> +class RawCategoryField extends AbstractCategoryField implements OptionsFieldInterface
je préfère sans l'implements

2017-05-12 09:54 UTC, MonsieurLuge commented
Les derniers retours ont été corrigés. Le code peut être réintégré (sauf autres retours, évidemment)

2017-05-12 09:59 UTC, jdm-web approved these changes

2017-05-12 09:59 UTC, merged